"""create games table

Revision ID: 0556b14c5801
Revises: 
Create Date: 2026-09-14 18:44:52.106791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0556b14c5801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('game_modes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('igdb_rating', sa.Float(), nullable=True),
    sa.Column('igdb_rating_count', sa.Integer(), nullable=True),
    sa.Column('similar_game_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('hltb_main', sa.Float(), nullable=True),
    sa.Column('hltb_main_extra', sa.Float(), nullable=True),
    sa.Column('hltb_completionist', sa.Float(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('story_gameplay_ratio', sa.Float(), nullable=True),
    sa.Column('content_warnings', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
