"""phase 6: add steam_appid to games, add user_library_items table

Revision ID: 29457369f226
Revises: d533896240f8
Create Date: 2026-10-04 15:26:02.941889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29457369f226'
down_revision: Union[str, None] = 'd533896240f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_library_user_game')
    )
    op.create_index(op.f('ix_user_library_items_user_id'), 'user_library_items', ['user_id'], unique=False)
    op.add_column('games', sa.Column('steam_appid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_steam_appid'), 'games', ['steam_appid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_steam_appid'), table_name='games')
    op.drop_column('games', 'steam_appid')
    op.drop_index(op.f('ix_user_library_items_user_id'), table_name='user_library_items')
    op.drop_table('user_library_items')
    # ### end Alembic commands ###
