"""add curated_list_games table

Revision ID: 563d399f40ca
Revises: 6dd924e0c57f
Create Date: 2026-09-30 18:11:09.075882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '563d399f40ca'
down_revision: Union[str, None] = '6dd924e0c57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_list_games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curated_list_games')
    # ### end Alembic commands ###
