"""add igdb_collections column

Revision ID: 6a6df71ee868
Revises: 563d399f40ca
Create Date: 2026-09-30 18:51:23.033391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6a6df71ee868'
down_revision: Union[str, None] = '563d399f40ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required - this ALTER TABLE runs against the
    # existing non-empty games table, same gotcha as custom_categories'
    # migration (see that file).
    op.add_column(
        'games',
        sa.Column('igdb_collections', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'igdb_collections')
    # ### end Alembic commands ###
