"""add richer enrichment fields (v3)

Revision ID: 6dd924e0c57f
Revises: e779056e23b3
Create Date: 2026-09-22 15:51:13.424760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6dd924e0c57f'
down_revision: Union[str, None] = 'e779056e23b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('pacing_score', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('mechanical_execution_focus', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('core_loop', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('tone_atmosphere', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('narrative_style', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('player_fit', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('player_fit_mismatch', sa.Text(), nullable=True))
    # server_default required (not just at the ORM level) - this ALTER TABLE
    # runs against the existing 500-row games table, same gotcha as the
    # custom_categories/backloggd_top_100 migrations before it.
    op.add_column(
        'games', sa.Column('standout_strengths', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}')
    )
    op.add_column(
        'games', sa.Column('common_complaints', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}')
    )
    op.add_column(
        'games', sa.Column('comparable_games', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'comparable_games')
    op.drop_column('games', 'common_complaints')
    op.drop_column('games', 'standout_strengths')
    op.drop_column('games', 'player_fit_mismatch')
    op.drop_column('games', 'player_fit')
    op.drop_column('games', 'narrative_style')
    op.drop_column('games', 'tone_atmosphere')
    op.drop_column('games', 'core_loop')
    op.drop_column('games', 'mechanical_execution_focus')
    op.drop_column('games', 'pacing_score')
    # ### end Alembic commands ###
