"""drop difficulty_score column

Revision ID: 9d7e864449f4
Revises: 0556b14c5801
Create Date: 2026-09-14 19:52:54.401774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d7e864449f4'
down_revision: Union[str, None] = '0556b14c5801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'difficulty_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('difficulty_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
