"""add cover_image_id column

Revision ID: affcffbe76f7
Revises: 4118f2cd1ae0
Create Date: 2026-10-07 18:02:08.435514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'affcffbe76f7'
down_revision: Union[str, None] = '4118f2cd1ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('cover_image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'cover_image_id')
    # ### end Alembic commands ###
