"""add custom_categories column

Revision ID: c65ffbed8d5f
Revises: 528f36a23acd
Create Date: 2026-09-16 21:34:20.467068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c65ffbed8d5f'
down_revision: Union[str, None] = '528f36a23acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here (not just at the ORM level) because
    # this ALTER TABLE runs against the existing 500-row games table - a
    # NOT NULL column with no default would fail immediately. The original
    # genres/platforms/etc. NOT NULL ARRAY columns didn't need this because
    # they were part of the initial CREATE TABLE on an empty table.
    op.add_column(
        'games',
        sa.Column('custom_categories', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'custom_categories')
    # ### end Alembic commands ###
