"""add igdb_category column

Revision ID: cb694cb898a1
Revises: 9d7e864449f4
Create Date: 2026-09-15 18:15:55.682971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb694cb898a1'
down_revision: Union[str, None] = '9d7e864449f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('igdb_category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'igdb_category')
    # ### end Alembic commands ###
